export const setAllTicketsFilter = () => ({ type: 'ALL_TICKETS' })
export const setWithoutTransferFilter = () => ({ type: 'WITHOUT_TRANSFER' })
export const setOneTransferFilter = () => ({ type: 'ONE_TRANSFER' })
export const setTwoTransferFilter = () => ({ type: 'TWO_TRANSFER' })
export const setThreeTransferFilter = () => ({ type: 'THREE_TRANSFER' })
export const setCheapest = () => ({ type: 'CHEAPEST' })
export const setFastest = () => ({ type: 'FASTEST' })
